import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
import Products from "../src/components/Products";
import Cart from "../src/components/Cart";
import { useData } from "../src/util/context";
import { useEffect } from "react";

export default function Home({ products }) {
  const { dispatch } = useData();

  // useEffect(() => {
  //   dispatch({ type: "products", payload: products });
  // }, [products]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Products products={products}/>
        <Cart />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await axios.get("https://dummyjson.com/products");
  console.log('revalidate')
  return {
    props: { products: data.products }, // will be passed to the page component as props
    revalidate: 10, // In seconds
  };
}
